version: '3.9'
name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    volumes:
      - ./server/config.ini:/config.ini

  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
      - CLI_LOG_LEVEL=DEBUG
      - CLI_NAME=Santiago Lionel
      - CLI_SURNAME=Lorca
      - CLI_DOCUMENT=30904465
      - CLI_BIRTHDATE=1999-03-17
      - CLI_NUMBER=7574
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client/config.yaml:/config.yaml

  client2:
    container_name: client2
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=2
      - CLI_LOG_LEVEL=DEBUG
      - CLI_NAME=Agustin
      - CLI_SURNAME=Zambrano
      - CLI_DOCUMENT=20563073
      - CLI_BIRTHDATE=2000-05-23
      - CLI_NUMBER=5368
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client/config.yaml:/config.yaml

  client3:
    container_name: client3
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=3
      - CLI_LOG_LEVEL=DEBUG
      - CLI_NAME=Ana
      - CLI_SURNAME=Mancuso
      - CLI_DOCUMENT=23793663
      - CLI_BIRTHDATE=1989-01-10
      - CLI_NUMBER=9023
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client/config.yaml:/config.yaml

  client4:
    container_name: client4
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=4
      - CLI_LOG_LEVEL=DEBUG
      - CLI_NAME=Sol
      - CLI_SURNAME=Caseres
      - CLI_DOCUMENT=40230523
      - CLI_BIRTHDATE=2003-09-02
      - CLI_NUMBER=3258
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client/config.yaml:/config.yaml

  client5:
    container_name: client5
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=5
      - CLI_LOG_LEVEL=DEBUG
      - CLI_NAME=Alan
      - CLI_SURNAME=Santana
      - CLI_DOCUMENT=36893032
      - CLI_BIRTHDATE=1995-10-25
      - CLI_NUMBER=534
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client/config.yaml:/config.yaml

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
