{# templates/docker-compose-clients.yaml #}
version: '3.9'
name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net

{% for i in range(1,clients + 1) %}
  client{{i}}:
    container_name: client{{i}}
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID={{i}}
      - CLI_LOG_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - server
{% endfor %}

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
